INSERT INTO Servicios (Ser_Nombre, Ser_Descripcion) VALUES
('Limpieza', 'Servicio de limpieza general'),
('Jardinería', 'Cuidado de jardines y plantas'),
('Transporte', 'Servicios de mudanza y transporte'),
('Plomería', 'Reparaciones de fontanería'),
('Electricidad', 'Servicios eléctricos y reparaciones'),
('Pintura', 'Pintura de interiores y exteriores'),
('Mantenimiento', 'Servicios de mantenimiento general');

INSERT INTO Manzanas (Man_Nombre, Man_Direccion) VALUES
('Bosa', 'Calle Falsa 123'),
('Suba', 'Avenida Principal 456'),
('Chapinero', 'Boulevard de la Paz 789');
